filter:
    paths:
        - EventListener/*
        - Resetter/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        enabled: true
        runs: 1
