language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml --colors

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
